export const URL = 'https://soud-cloud-backend.herokuapp.com'
export const logout = '/api/user/logout/'
export const resetPassword = '/user/password_reset/'
export const signin = '/api/user/login/'
export const signup = '/api/user/create/'
export const listSongs = '/api/song/list/'
export const searchSongs= '/api/song/search/?q='
export const viewComments = '/api/song/details/'
export const addComment = '/api/song/comment/create/'
export const updateComment = '/api/song/comment/update/'
export const deleteComment = '/api/song/comment/delete/'
export const like = '/api/song/like/'
export const unlike = '/api/song/remove_like/'
export const addView = '/api/song/increment_view_count/'
export const viewLiked = '/api/song/liked_songs/'
export const share = '/api/song/share/'