export const URL = 'https://soud-cloud-backend.herokuapp.com'
export const logout = '/api/user/logout/'
export const resetPassword = '/user/password_reset/'
export const signin = '/api/user/login/'
export const signup = '/api/user/create/'
export const listSongs = '/api/song/list/'
export const searchSongs= '/api/song/search/?q='
export const viewComments = '/api/song/details/'